---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: trinity-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: silica5518/t-dev-701-backend:prod-2a0e0d96
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: trinity-config
        - secretRef:
            name: trinity-secrets

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10