---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: trinity-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: silica5518/t-dev-701-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: trinity-config
        - secretRef:
            name: trinity-secrets
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: postgres-password
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10