apiVersion: v1
kind: ConfigMap
metadata:
  name: trinity-config
  namespace: trinity-prod
data:
  JWT_EXPIRATION: "86400000"
  NEXT_DEV_API_URL: "http://backend-service.trinity.svc.cluster.local:8080"
  NEXT_PROD_API_URL: "http://backend-service.trinity.svc.cluster.local:8080"
  PAYPAL_CLIENT_ID: ""
  SPRING_CORS_ALLOWED_ORIGINS: "http://frontend-service.trinity.svc.cluster.local:3000"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.trinity.svc.cluster.local:5432/mydatabase"
  SPRING_DATASOURCE_USERNAME: "myuser"