---
apiVersion: v1
kind: Secret
metadata:
  name: trinity-secrets
  namespace: trinity-prod
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: c3VwZXJTZWNyZXQ=
  SPRING_JWT_SECRET: YjI0YmZlMDViMTBmODc2MTcyMDk0ZmZhNTQyZGQxMGI0MzQzN2NkOTkzNGQ5NWM4NDRhNTAwNmU1MWE4MDM4YQo=
  SPRING_PAYPAL_SECRET: ""
