# The names and order of the pipeline stages.
stages:
  - setup
  - build
  - test
  - package
  - deploy

variables:
  FRONTEND_IMAGE: "${DOCKER_HUB_USERNAME}/t-dev-701-frontend"
  NODE_VERSION: "20.10.0"

###############
# BUILD STAGE #
###############

Build Frontend dev image:
  stage: build
  variables:
    FRONTEND_IMAGE_TAG_DEV: "${FRONTEND_IMAGE}:dev-${CI_COMMIT_SHORT_SHA}"
  # Scripts
  before_script:
    - echo $DOCKER_HUB_USERNAME
    - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  script:
    - echo $DOCKER_HUB_USERNAME
    - echo $FRONTEND_IMAGE_TAG_DEV
    - cd frontend
    - docker build --tag $FRONTEND_IMAGE_TAG_DEV --build-arg NEXT_PUBLIC_ENVIRONMENT=dev --file Dockerfile --target dev .
    - docker push $FRONTEND_IMAGE_TAG_DEV
  after_script:
    - docker image rm $FRONTEND_IMAGE_TAG_DEV

##############
# TEST STAGE #
##############

Lint Frontend codebase:
  stage: test
  variables:
    FRONTEND_IMAGE_DEV_TAG: $FRONTEND_IMAGE:dev-$CI_COMMIT_SHORT_SHA
  script:
    - docker run --rm
        -v $(pwd)/frontend/:/app/
        -e CI=1
        $FRONTEND_IMAGE_DEV_TAG
        lint
  needs: ['Build Frontend dev image']


Run Frontend tests:
  stage: test
  variables:
    FRONTEND_IMAGE_DEV_TAG: $FRONTEND_IMAGE:dev-$CI_COMMIT_SHORT_SHA
  script:
    - mkdir -p frontend/reports
    - docker run --rm
        -v $(pwd)/frontend/reports:/app/reports/
        -v $(pwd)/frontend/:/app/
        -e CI=1
        $FRONTEND_IMAGE_DEV_TAG
        test
    - docker run --rm
        -v $(pwd)/frontend/reports:/app/reports/
        -v $(pwd)/frontend/:/app/
        -e CI=1
        $FRONTEND_IMAGE_DEV_TAG
        test:coverage
  artifacts:
    reports:
      junit: frontend/reports/report.xml
    expire_in: 1 week
  needs: ['Build Frontend dev image']

#################
# PACKAGE STAGE #
#################


Build Frontend prod image:
  # Please check the 'default' directives in ../.gitlab-ci.yml to understand the full Job config
  stage: package
  variables:
    FRONTEND_IMAGE_TAG_PROD: ${FRONTEND_IMAGE}:prod-${CI_COMMIT_SHORT_SHA}
  # Scripts
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  script:
    - cd frontend
    - docker build 
        -t $FRONTEND_IMAGE_TAG_PROD 
        -t ${FRONTEND_IMAGE}:latest
        --build-arg NEXT_PUBLIC_ENVIRONMENT=production
        --file Dockerfile
        --target prod
        . # The '.' is the path the Dockerfile directory.
    - docker push $FRONTEND_IMAGE_TAG_PROD
    - docker push ${FRONTEND_IMAGE}:latest
  after_script:
    - docker image rm $FRONTEND_IMAGE_TAG_PROD
    - docker image rm ${FRONTEND_IMAGE}:latest
  # Conditions
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Build Frontend draft image:
  stage: package
  variables:
    FRONTEND_IMAGE_TAG_DRAFT: ${FRONTEND_IMAGE}:draft-${CI_MERGE_REQUEST_IID}

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - cd frontend
    - docker build 
        --tag $FRONTEND_IMAGE_TAG_DRAFT
        --build-arg NEXT_PUBLIC_ENVIRONMENT=draft
        --file Dockerfile
        --target prod
        .
    - docker push $FRONTEND_IMAGE_TAG_DRAFT
  after_script:
    - docker image rm $FRONTEND_IMAGE_TAG_DRAFT
  rules:
    - if: $CI_MERGE_REQUEST_IID


################
# DEPLOY STAGE #
################

Deploy Frontend to prod env:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL"
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/${CI_COMMIT_TAG}/g" kubernetes/frontend-production-deployment.yaml
    - kubectl apply -f kubernetes/frontend-production-deployment.yaml
  only:
    - tags
  when: manual