default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - frontend/node_modules/
      - frontend/.next/cache/
    policy: pull-push
  tags:
    - k8s

stages:
  - test
  - package
  - deploy

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  NODE_OPTIONS: "--max-old-space-size=4096"
  FRONTEND_IMAGE: $DOCKER_HUB_USERNAME/t-dev-701-frontend

Run Frontend unit-tests:
  stage: test
  image: node:18-alpine
  before_script:
    - cd frontend
    - apk add --no-cache git
    - npm ci
  script:
    - npm run test:coverage
  artifacts:
    when: always
    reports:
      junit: frontend/reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: frontend/reports/coverage/cobertura-coverage.xml
    paths:
      - frontend/reports/coverage/
      - frontend/reports/
    expire_in: 1 week

Sonar Analysis:
  stage: test
  image: node:18-alpine
  before_script:
    - cd frontend
    - apk add --no-cache git
    - npm ci
    - apk add --no-cache nodejs npm
  script:
    - npm run sonar 
  needs:
    - Run Frontend unit-tests
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Build the Frontend prod image:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    FRONTEND_IMAGE_TAG_PROD: $FRONTEND_IMAGE:prod-$CI_COMMIT_SHORT_SHA
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_HUB_USERNAME\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context="./frontend"
      --dockerfile="./frontend/Dockerfile"
      --target="prod"
      --destination="$FRONTEND_IMAGE_TAG_PROD"
      --destination="$FRONTEND_IMAGE:latest"
      --cache=true
      --cache-ttl=24h
      --build-arg="NEXT_PUBLIC_ENVIRONMENT=production"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Update the ArgoCD deployment file:
  stage: deploy
  image: alpine:latest
  variables:
    FRONTEND_IMAGE_TAG_PROD: $FRONTEND_IMAGE:prod-$CI_COMMIT_SHORT_SHA
  before_script:
    - apk add --no-cache git
    - git config --global user.email "gitlab-ci@epitech-msc2026.me"
    - git config --global user.name "GitLab CI"
  script:
    - |
      cd deployment/trinity && \
      sed -i "s|image:.*|image: ${FRONTEND_IMAGE_TAG_PROD}|" frontend-deployment.yaml && \
      git add frontend-deployment.yaml && \
      git commit -m "Update frontend image to ${FRONTEND_IMAGE_TAG_PROD} [skip ci]" && \
      git push "https://oauth2:${GITOPS_CI_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_DEFAULT_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH