stages:
  - install
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - cd frontend
    - echo "📦 Installing dependencies..."
    - npm install
    - echo "🧪 Running tests..."
    - npm test
    - echo "✅ Tests passed successfully"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(noah|elone|gabriel|rabieh|geraud)\/.*/ || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

build_docker_image:
  stage: build
  script:
    - docker build -f ./my-app/DockerFile.dev -t my-app .
  only:
    - main

deploy_application:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main
