stages:
  - install
  - test
  - build
  - deploy

# Install dependencies and run tests
install_dependencies:
  stage: install
  script:
    - npm install
    - npm test # Replace with your test command if you have one
  only:
    - dev # Run on dev branch

# Build Docker image
build_docker_image:
  stage: build
  script:
    - docker build -f ./my-app/DockerFile.dev -t my-app .
  only:
    - main # Only run on the main branch

# Simulate deployment (you can add real deployment logic later)
deploy_application:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main # Only run on the main branch
