# Each default keyword is copied to every job that doesn’t already have it defined. 
default:
  image: eclipse-temurin:21-jdk-jammy
  cache:
    paths:
      - .m2/repository
      - backend/target/

# Use include to include external YAML files in your CI/CD configuration. 
include:
  - local: frontend/frontend-ci.yml
    rules:
      - changes: 
        - frontend/**/*

  - local: backend/backend-ci.yml
    rules:
      - changes: 
        - backend/**/*

# The names and order of the pipeline stages.
stages:
  - setup
  - build
  - test
  - package 
  - publish
  - clean
  - deploy

# Control what types of pipeline run. 
workflow:
  rules:
    # Run only for MR, tagged or protected branches
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    # Enforce branch naming rules
    - if: $CI_COMMIT_BRANCH =~ /^(noah|elone|gabriel|rabieh|geraud)\/.*/ || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

Logger:
  stage: setup 
  script: 
    - echo "Running the T-DEV-701-DevOps CI"