default:
  tags:
    - k8s
  image: alpine:latest 

include:
  - local: frontend/frontend-ci.yml
    rules:
      - changes:
        - frontend/**/*
  - local: backend/backend-ci.yml
    rules:
      - changes:
        - backend/**/*

stages:
  - setup
  - test
  - package
  - deploy

variables:
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_CPU_LIMIT: "2"
  KUBERNETES_MEMORY_REQUEST: "1Gi"
  KUBERNETES_MEMORY_LIMIT: "2Gi"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_COMMIT_BRANCH =~ /^(noah|elone|gabriel|rabieh|geraud)\/.*/ || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

Logger:
  stage: setup
  script:
    - echo "Running the T-DEV-701-DevOps CI"