services:
  postgres:
    image: 'postgres:15-alpine'

    # Label used by spring-boot-docker-compose library
    labels:
      org.springframework.boot.service-connection: postgres

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}

    ports:
      - '5432:5432'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5