services:
  rabbitmq:
    image: 'rabbitmq:latest'

    labels:
      org.springframework.boot.service-connection: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: /run/secrets/rabbitmq_password 

    ports:
      - 5672:5672 # Standard AMQP port
      - 15672:15672 # Management UI port

    volumes:
    - rabbitmq_data:/var/lib/rabbitmq

    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_management && rabbitmq-server"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
