services:
  rabbitmq:
    image: 'rabbitmq:latest'

    labels:
      org.springframework.boot.service-connection: rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

    ports:
      - 5672:5672 # Standard AMQP port
      - 15672:15672 # Management UI port

    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_management && rabbitmq-server"

    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:15672 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s