apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: argocd
data:
  ssh_known_hosts: |
    t-dev.epitest.eu ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbgKhNRqJhW8crG1nszOaCxAA5OgiKxjx7YA1RwqbcFyZCYSaX22tSwEbJwyiJD4lqv8czR58oUG8GfNX49dAXndqzqf1tyP7jx6uvAbfFXkxbmdn1mC9HBfOb52eTYixrkL8lR4fQd+xRyLCe158ukyX/ohmlU7uMsjS6eS07qAXlPrpLuL4NiX+0P0FLGnQCgYVbPK0teAU50pvuG1lYbaz7+9kZLHMk12AZuTLctVuQcgYChk8xXRsEwD72tG8kQYxJEYLHMtGRqq/N2wesPE09P5rI3nqn4hAMEAo2kCWcyMBCqhd3Hd3vaxEn9W9IGdaYVDpXvMNL29tYGu3EiFp5ahlBkmfdxaQqHpazWnrPv+tczte7UV8mJhbw4tFg82cwuBd1tdYpvYwf1I/NOaluFerU/VyCRzUfXGNIbnWfm60vT1xxeaDPuZ1hbxp3z9NEqJL3NDfCaQq/TYK0MpMe85kmchisi4Uxr1JMWhzkaty3CLT0b6ivnB524cE=
    t-dev.epitest.eu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHVIdg3KXtbNbaojFFDkDOG7Inn79p3BG4zmVUrbccB28K/dn9eWG3L8FXIngit9gYuIizsDo4jpqx8KyTZTgqg=
    t-dev.epitest.eu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBLcGxhCC5zSWUrloOXk2fdW2ATIg59N6+TytmOhsotf