apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@t-dev.epitest.eu:PAR_11/T-DEV-703-Mobile.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    < THE PRIVATE KEY OWNED BY GABRIEL >
    -----END OPENSSH PRIVATE KEY-----