community:
  enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - name: sonarqube.trinity.epitech-msc2026.me
      path: /
  tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.trinity.epitech-msc2026.me

persistence:
  enabled: true
  storageClass: "standard-rwo"

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

postgresql:
  enabled: true
  persistence:
    enabled: true
    storageClass: "standard-rwo"

monitoringPasscode: "my-monitoring-passcode"
