---
- name: Setup GitLab Runner on EC2
  hosts: ec2_gitlab_runner
  become: yes
  vars:
    gitlab_runner_url: "https://t-dev.epitest.eu/"
    gitlab_runner_token: "GR13489412H_5ZcrZRxD7fDbL_Vxm"
    gitlab_runner_name: "EC2 Gitlab Runner"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install GitLab Runner
      shell: |
        curl -L --output /usr/local/bin/gitlab-runner \
        https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
        chmod +x /usr/local/bin/gitlab-runner
        gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
        gitlab-runner start

    - name: Add gitlab-runner to docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes

    - name: Create GitLab Runner config directory
      file:
        path: /etc/gitlab-runner
        state: directory

    - name: Register GitLab Runner
      shell: |
        gitlab-runner register \
          --non-interactive \
          --url "{{ gitlab_runner_url }}" \
          --registration-token "{{ gitlab_runner_token }}" \
          --name "{{ gitlab_runner_name }}" \
          --executor "docker" \
          --docker-image "docker:latest" \
          --docker-privileged "false" \
          --docker-volumes "/var/run/docker.sock:/var/run/docker.sock"

    - name: Restart GitLab Runner
      systemd:
        name: gitlab-runner
        state: restarted