spring:
  # Application Name
  application:
    name: ${SPRING_APP_NAME:t-dev-701-backend-api}

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Web Configuration
  web:
    resources:
      add-mappings: false

# Server Configuration
server:
  error:
    whitelabel:
      enabled: false

# Management (Actuator) Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org:
      springframework: DEBUG
      hibernate: ERROR

# JWT Configuration (New)
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# API URL Configuration
api:
  url: ${NEXT_PUBLIC_API_URL}

app:
  cors:
    allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS}

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    use-root-path: false
    url: /api/v1/api-docs
    config-url: /api/v1/api-docs/swagger-config
  pathsToMatch: /api/v1/**

# PayPal Configuration
paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_SECRET}
  mode: live