#############################
# Spring Boot Configuration #
#############################
spring:
  application:
    name: ${SPRING_APP_NAME:t-dev-701-backend-api}
    version: ${SPRING_APP_VERSION:0.0.1-SNAPSHOT}
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB:trinity}
    username: ${POSTGRES_USER:trinity}
    password: ${POSTGRES_PASSWORD:trinity}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true

  # Web Configuration
  web:
    resources:
      add-mappings: false

########################
# Server Configuration #
########################
server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
      hibernate: ERROR

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

app:
  cors:
    allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS:*}


springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    use-root-path: false
    url: /api/v1/api-docs
    config-url: /api/v1/api-docs/swagger-config
  pathsToMatch: /api/v1/**


springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    use-root-path: false
    url: /api/v1/api-docs
    config-url: /api/v1/api-docs/swagger-config
  pathsToMatch: /api/v1/**

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_SECRET}
  mode: sandbox