#####################################
# Spring Boot Configuration
#####################################
spring:
  application:
    name: ${SPRING_APP_NAME}
    version: ${SPRING_APP_VERSION:0.0.1-SNAPSHOT}

  #####################################
  ### Database Configuration
  #####################################
  datasource:
    url: ${SPRING_DATASOURCE_URL} 
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #####################################
  # JPA/Hibernate Configuration
  #####################################
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #####################################
  ### DevTools Configuration
  #####################################
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true

  #####################################
  ### Web Configuration
  #####################################
  web:
    resources:
      add-mappings: false

########################
# Server Configuration #
########################
server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#####################################
# Logging Configuration
#####################################
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
      hibernate: ERROR

#####################################
# JWT Configuration
#####################################
jwt:
  secret: ${SPRING_JWT_SECRET}
  expiration: ${SPRING_JWT_EXPIRATION}

#####################################
# CORS Configuration
#####################################
app:
  cors:
    allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS}

#####################################
# Swagger Configuration
#####################################
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    use-root-path: false
    url: /api/v1/api-docs
    config-url: /api/v1/api-docs/swagger-config
  pathsToMatch: /api/v1/**

#####################################
# Paypal Configuration
#####################################
paypal:
  client:
    id: ${SPRING_PAYPAL_CLIENT_ID}
    secret: ${SPRING_PAYPAL_CLIENT_SECRET}
  mode: sandbox