# Application Name
spring:
  application:
    name: ${SPRING_APP_NAME:t-dev-701-backend-api}
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB:trinity}
    username: ${POSTGRES_USER:trinity}
    password: ${POSTGRES_PASSWORD:trinity}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true

  # Web Configuration
  web:
    resources:
      add-mappings: false

# Server Configuration
server:
  error:
    whitelabel:
      enabled: false

# Management (Actuator) Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
      hibernate: ERROR

# JWT Configuration (New)
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    disable-swagger-default-url: true
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: true
  packages-to-scan: com.trinity
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match:
    - /api/**

app:
  cors:
    allowed-origins: ${NEXT_DEV_API_URL}

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_SECRET}
  mode: sandbox